version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/app_build
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install --production
      - run: npm install -g @angular/cli
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths:
            - src/
            - public/
            - package.json
            - node_modules/
  unit_test:
    working_directory: ~/app_build
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: ~/app_build
      - run: npm test

  deploy:
    machine:
        enabled: true
    working_directory: ~/app_build
    environment:
      HEROKU_APP: "cinewebpw"
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  main:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - deploy:
          requires:
            - unit_test